/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Utbot
{
    public class LyftProScanZone : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "utbot_msgs/LyftProScanZone";

        public string name;

        public float x_offset;
        public float y_offset;

        public float width;
        public float height;

        public LyftProScanZone()
        {
            this.name = "";
            this.x_offset = 0.0f;
            this.y_offset = 0.0f;
            this.width = 0.0f;
            this.height = 0.0f;
        }

        public LyftProScanZone(string name, float x_offset, float y_offset, float width, float height)
        {
            this.name = name;
            this.x_offset = x_offset;
            this.y_offset = y_offset;
            this.width = width;
            this.height = height;
        }
    }
}
