/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Utbot
{
    public class CreateLyftProScanZoneRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "utbot_msgs/CreateLyftProScanZone";

        public LyftProScanZone scan_zone_params;

        public bool duplicate_previous;

        public CreateLyftProScanZoneRequest()
        {
            this.scan_zone_params = new LyftProScanZone();
            this.duplicate_previous = false;
        }

        public CreateLyftProScanZoneRequest(LyftProScanZone scan_zone_params, bool duplicate_previous)
        {
            this.scan_zone_params = scan_zone_params;
            this.duplicate_previous = duplicate_previous;
        }
    }
}
