/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Utbot
{
    public class CreateLyftProScanZoneResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "utbot_msgs/CreateLyftProScanZone";

        public bool success;
        //  True if the call succeeded
        public string message;
        //  Used to give details about success

        public CreateLyftProScanZoneResponse()
        {
            this.success = false;
            this.message = "";
        }

        public CreateLyftProScanZoneResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }
    }
}
